### ISSUE TITLE
Just little typographies bugs

### ISSUE THREAD

**Issue by user67x** [SergeyMosin/Appointments#127]
Hi. I finished all the new translations that were pending with the new version of appointment, but I still notice these little typographical errors for the French translation: the & n b s p (in one word) is not transliterated for the following text strings:

Form Title
Show appointments for next
Main calendar
Time slot mode

Thank you very much

**Comment by user67x** [comment]
The text string 'Public Page Preview' should be translatable too.

**Comment by SergeyMosin** [comment]
Thanks, I'll do an other update with the latest translations in the next couple of days. Let me know (sergey[at]srgdev.com) where I can send your contributor key.

**Comment by SergeyMosin** [comment]
v1.7.3 should have the latest translations from transifex

**Comment by user67x** [comment]
Hi Sergey,
Here are the nbsp problems and two little bugs.

Regards

![2020-09-22_17-05-07](https://user-images.githubusercontent.com/13274746/93902887-608a8080-fcf8-11ea-926b-5fb9fb65e7d9.png)
![2020-09-22_17-12-43](https://user-images.githubusercontent.com/13274746/93902893-61231700-fcf8-11ea-9e1d-6ae09832634b.png)
![2020-09-22_17-08-54](https://user-images.githubusercontent.com/13274746/93902894-61bbad80-fcf8-11ea-8812-ced696463554.png)
![2020-09-22_17-07-37](https://user-images.githubusercontent.com/13274746/93902896-62ecda80-fcf8-11ea-96b2-0418077a6eea.png)
![2020-09-22_17-06-40](https://user-images.githubusercontent.com/13274746/93902903-63857100-fcf8-11ea-9ddc-3626c43893b4.png)

**Comment by SergeyMosin** [comment]
I see, you are trying to put a space between the end word and ``:`` and other punctuations by using ``&nbsp`` character. **This will not work, because special characters get encode for security reasons.**
For example:

![appt-translations](https://user-images.githubusercontent.com/10747559/94045206-22936800-fd9d-11ea-847e-42f65199bb4c.jpg)

It works for ``Email:`` when you are using regular space because the ``:`` is inside the string provide by the translation function. In case with the ``Form Title`` I left the ``:`` outside by accident. If I get som free time I'll try to normalize the ``:`` inclusions.
