### ISSUE TITLE
Making two Appointments at same time

### ISSUE THREAD

**Issue by wondrousturtle** [SergeyMosin/Appointments#130]
Thank you for your awesome tool! I tried various open source alternatives and settled on this one because it allowed me the most flexibilty!

I have encountered only one bug: I want to offer two appointment slots at the same time.
I create two events in the calender, and they both show up in the appointment booking page. But once I book one of them, the other one becomes unavailable as well.

I tried to change the time of the second one to 5 minutes later, but to no avail.
I tried giving them different titles, booking it without verifying the email, booking with verifying the email, nothing makes the second timeslot become visible.
If I cancel the appointment, both become visible again.

I am using the external mode, with the "Auto-fix "Source" timeslots" option enabled.

**Comment by SergeyMosin** [comment]
Overlapping time slots are not possible for the **same calendar** in the ``external mode``.

If you are trying to have multiple attendees for the same appointment it is not supported yet, but there is a feature request here: #54 

I am not sure if this will work for your situation, but you can have two different public pages (supported since v1.7.3) and have the **same**  ``Source Calendar`` and **two different**  ``Destination Calendars``

**Comment by SergeyMosin** [comment]
Tagging #87 and #54
