### ISSUE TITLE
Send confirmation email in user locale

### ISSUE THREAD

**Issue by nijel** [SergeyMosin/Appointments#158]
When somebody books an appointment, I will get a confirmation email localized in his language. It's not that big deal as all information is also added to my calendar, but still, I would prefer to receive email in language I understand rather than in language that the other person prefers.

To reproduce:

* Use English in Nextcloud
* Configure appointments
* Enable: Email Me when an appointment is: Confirmed
* Let somebody with browser configured to German confirm an appointment
* You will receive: "Termin bestätigt: Name Surname, 26.11.20, 15:15"

**Comment by nooblag** [comment]
Yes, it would be great if this plugin used the Nextcloud `default_locale` config.php setting.

**Comment by ccoenen** [comment]
The same thing regularly happens to me. My students use nextcloud in any language they prefer (as they should!) and I get notifications in their languages, too. It's fine because I get a lot of them and I know how to read them, but it would be better if I received them in my language instead.

![grafik](https://github.com/user-attachments/assets/a7ee08b8-31d3-45b7-9a7a-249da7fdd5b5)

(same for localisation of date/time, of course, but that's a different issue)

**Comment by SergeyMosin** [comment]
fixed in v2.2.0
