### ISSUE TITLE
Appointments not displayed in the iframe

### ISSUE THREAD

**Issue by Vince2956** [SergeyMosin/Appointments#191]
I have this problem, and I am not able to integrate tutorial 10. iFrame/Embedding of the manual. Do you have a precise description of the steps to follow ? I use a hosted Nextcloud, I can’t change the configuration of the Nextcloud itself. My technical department asked me to contact you.
https://help.nextcloud.com/t/appointments-not-displayed-in-the-iframe/110698

**Comment by Vince2956** [comment]
I dont understand wath is the "**emb_afad**_YourUserName" and the "**emb_cncf**_YourUserName" ? 
Is it the same username? the one I use to log into my nextcloud account ?

For exemple if my UserName is "admin123" and my.domain.com is "https://123456.fr", I must execute the following commands :
1  occ to set allowed Frame Ancestor Domain :
`php occ config:app:set appointments "emb_afad_admin123" --value "https://123456.fr"`

2 Use occ to set base URL
` php occ config:app:set appointments "emb_cncf_admin123" --value "https://123456.fr/page_url?some_param_name=" `

**Comment by SergeyMosin** [comment]
Do you still need help with this ?

**Comment by Vince2956** [comment]
I succeeded. Thank.

**Comment by MickGe** [comment]
Because I couldn't use PHP, I use Javascript. Here my method if it could help someone…

- `<PROVIDED_EMBEDDABLE_URL>` is the provided embeddable url from Appointment app in Nextcloud.
- `<PATH_TO_NEXTCLOUD_DIRECTORY>` is the path to Nextcloud on the server, something like *`/var/www/html/nextcloud`*
- `<Nextcloud_username>` is the username of the user who create the appointment (it must be lowercase).
- `<MY_DESTINATION_DOMMAIN.COM>` the domain URL of the destination page.
- `<PAGE_PATH>` is the path to the page which contains the iframe, if it’s the main page remove it.

## In the destination page source code

Insert the iframe tag in the destination page.

```html
<iframe id="myAppointmentFrame" title="Appointment form" frameborder="0" style="height: 100rem; width: 100%;" src=
"<PROVIDED_EMBEDDABLE_URL>" name="myAppointmentFrame"></iframe>
```

If  `id` is changed, it must be changed in the script.

## On the server

Set allowed Frame Ancestor Domain.

```bash
sudo -u www-data php /<PATH_TO_NEXTCLOUD_DIRECTORY>/occ config:app:set appointments "emb_afad_<Nextcloud_username>" --value "https://<MY_DESTINATION_DOMMAIN.COM>"
```

Set base URL for the destination page URL.

```bash
sudo -u www-data php /<PATH_TO_NEXTCLOUD_DIRECTORY>/occ config:app:set appointments "emb_cncf_<Nextcloud_username>" --value "https://<MY_DESTINATION_DOMMAIN.COM>/<PAGE_PATH>/?apphash="
```

If `apphash` is renamed, it must be changed in the script.

## In the destination page source code

Insert the script tag in head tag of the destination page source code.

```javascript
<script type="text/javascript" async="async">

var urlRDV = window.location.href.includes('<PAGE_PATH>');

if (urlRDV) {
  window.addEventListener('DOMContentLoaded', function() {
    var src = "<PROVIDED_EMBEDDABLE_URL>";
    var appointmentParam = "apphash"

    function getUrlVars() {
      var vars = {};
      var parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi, function(m,key,value) {
        vars[key] = value;
      });
      return vars;
    };

    var params = getUrlVars();
    var apphash = params[appointmentParam];
    var paramsConcat = Object.entries(params).reduce(function (prev, curr) {
      if (curr[0] === appointmentParam) {
        return prev;
      }
      prev = prev.concat("&",curr[0].toString(),"=",curr[1].toString());
      return prev;
    }, "");

    if (apphash) {
      src = src.slice(0, -4).concat('cncf?d=').concat(apphash,paramsConcat);
     }

    var myIframe = document.getElementById('myAppointmentFrame');
    myIframe.src=src;
  })();
}

</script>
```
