### ISSUE TITLE
[Features] customise link to video app in mail

### ISSUE THREAD

**Issue by teger** [SergeyMosin/Appointments#210]
Hello,

Good plugin, very interesting !
Could you modify this plugin to authorize a link  to Jitsi video (example meet.jit.si) instead of a link to talk in email confirmation ?

Thanks for your response,

best regards

**Comment by SergeyMosin** [comment]
As of v1.12.6 it is possible to add HTML/links in Additional Email Text. Additionally there is a rudimentary extension system available for notifications, more https://github.com/SergeyMosin/Appointments/issues/26#issuecomment-1135863648

Closing because there is unlikely to be more 3rd party (Jitsi, Zoom, etc...) integration features development.
