### ISSUE TITLE
Nextcloud 22 compability

### ISSUE THREAD

**Issue by small1** [SergeyMosin/Appointments#225]
Hello,

Nextcloud 22 compability is needed. When testing on my test instance right now no emails are sent. And im guessing that the talk integration will need some fixing as well.

The strange thing is that i dont see anything that pops out in the nextcloud log.

**Comment by small1** [comment]
This could perhaps wait until the next Nextcloud talk is released within a few weeks.  As I'm guessing that it will break stuff as usual.

**Comment by Dom-Gabriel** [comment]
Same effect here. Since the update to Nextcloud 22, no confirmation emails are sent out when an appointment is set up. However, nothing can be seen, neither in the Nextcloud log, nor in /var/log/mail.info nor in /var/log/php_errors.log.

**Comment by SergeyMosin** [comment]
Thanks for the reports, looks like NC22 was officially released on June 6th. Next `appointments` release (in the next couple of days) should be fully compatible.

**Comment by orangesunny** [comment]
Hey @SergeyMosin, how does it look with the release? No mails and Talk rooms complicate my daily work. Can I help with testing or anything else?

**Comment by martin-77** [comment]
Same here - No mails are send. Log is empty.

**Comment by Bellusterra** [comment]
@SergeyMosin I would be happy to help test things too :)

**Comment by SergeyMosin** [comment]
Looks like emails and some form input labels were the only problems with NC22 compatibility.

v1.10.0 is nc22 compatible.

**Important:** I had to remove `:` from `Name:` , `Email:` and `Phone:`  because of this bug: https://github.com/nextcloud/server/issues/28347. Therefore, **translations** are **NOT** going to be available for this three labels until they are pushed from transifex. I'll do next couple of releases as soon as translations are available.

**Comment by martin-77** [comment]
Great Job, as far as I can see, the bug is resolved!

Thank you!

Martin

**Comment by orangesunny** [comment]
Work well, thank you, @SergeyMosin!

**Comment by Dom-Gabriel** [comment]
It works now (setting the appointment, confirmation, cancellation) :+1: . Thanks a lot, @SergeyMosin!
