### ISSUE TITLE
Support for Nextcloud 23

### ISSUE THREAD

**Issue by dolohow** [SergeyMosin/Appointments#270]
Nextcloud 23 is out :)

**Comment by leonardohlee** [comment]
follow up

**Comment by SergeyMosin** [comment]
v1.11.6 is NC23 compatible.

Additionally NC23 has own Appointment system in Calendar App now https://player.vimeo.com/video/650621426?h=5896b9b0bd&badge=0&autopause=0&player_id=0&app_id=58479 .

Going forward I think it does not make sense to have two apps doing the same thing. Therefore I'll either be porting features to NC native Appointments App or I will create something like "Appointments Extended" App that will act as advanced settings, features and customization options gateway for the native app.

Current Appointments App will still be maintained at least until NC23 EOL which is scheduled for 2022-11 according to this: https://docs.nextcloud.com/server/latest/admin_manual/release_schedule.html

**Comment by nolens** [comment]
`Therefore I'll either be porting features to NC native Appointments App or I will create something like "Appointments Extended" App that will act as advanced settings, features and customization options gateway for the native app.`

That sounds reasonable to me. 

At the same time, I am extremely worried that some of the excellent functionality of your app will get lost in this process - like: 

- "external mode"
- being able to delete, copy, move or add single appointment slots within my favorite calendar app

I am sure other hardcore users would have a lot to add to this list! 

@SergeyMosin, what do you think about opening a thread to collect users favorite features and workflows, to make sure none of those get lost in the transition to "Appointments Extended" App? 

Best
Tom

**Comment by nolens** [comment]
`Therefore I'll either be porting features to NC native Appointments App or I will create something like "Appointments Extended" App that will act as advanced settings, features and customization options gateway for the native app.`

@SergeyMosin 
I was just checking the new "appointment" functionality in NC 23. 

**It is nowhere near as functional** as this appointment app! 

In order to maintain similar functionality to this app, most of the functions would have to be ported to the new plugin, if you want to follow your plan... 

Any thoughts on this, Sergey?

Best regards
Tom

**Comment by okworx** [comment]
Just to point out, the Appointments app is super useful and a great time saver and I would be totally willing to further support the development (e.g. porting Appointments features to the native app) via purchasing another license or donation or something like that.
