### ISSUE TITLE
Google Meet / MSFT Teams Integration [Feature Request]

### ISSUE THREAD

**Issue by BRadHoc** [SergeyMosin/Appointments#286]
Hi,

I'm looking at using this for my appointment scheduling, however like the Talk integration, I'd like a similar integration using Google Meet.

Do you accept pull requests (or do you have any plans of this in your current roadmap?)

**Comment by SergeyMosin** [comment]
I think Appointments App integration with third-party services like `Google Meet` or `MSFT Teams` should be viewed as a two-part problem.

1. Creating and Managing third-party sign-ups, keys, auth/renewal tokens, API calls, etc..
2. Integration of API calls into Appointments App flow.

**Part 1** should be done as a separate NC App possibly somewhat similar to [BigBlueButton Integration](https://apps.nextcloud.com/apps/bbb) and ideally expose a simple `CRUD` Connector Interface maybe something like:
```php
interface MeetingsConnector
{
    // called when an appointment is created
    public function createMeeting(string $accountId, object $meeting): object;

    public function getMeeting(string $meetingId): object;

    // can be used when for example appointment time changes  
    public function updateMeeting(object $meeting): object;

    // called when an appointment is deleted
    public function deleteMeeting(string $meetingId);
}
```  
Keeping this as a separated app has the following advantages:
- No code bloat
- Easier to debug
- Other apps in NC ecosystem can use it !!!


**Part 2** would require minimal effort and would be just a copy of [TalkIntegration Class](https://github.com/SergeyMosin/Appointments/blob/master/lib/Backend/TalkIntegration.php) with some modifications.

Due to the lack of free time at the moment I will not be able to do **Part 1**, but I would be more then happy to add Appointments integration code when Part 1 is ready

**Comment by BRadHoc** [comment]
I've finished up a preliminary class for Google to start with, as the integration is only being used for video calling and there's no restriction on time for google meetings the only functions needed were create / delete (will test it out over the next week or so):

<img width="415" alt="Screenshot 2022-02-01 at 12 21 13 am" src="https://user-images.githubusercontent.com/52509751/151894574-1ab661ba-b071-4f58-9581-24d256974ee0.png">

**Comment by BRadHoc** [comment]
The other thing I'm unsure of is, where should I save a session key for OAuth relative to the user that's using the appointments app. Where do you store persistent per-user data?

**Comment by SergeyMosin** [comment]
As of v1.12.5 a rudimentary notification extension system is available, more info: https://github.com/SergeyMosin/Appointments/issues/26#issuecomment-1135863648
