### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [SergeyMosin/Appointments#356]
It would be great if you could set a limit of people who can participate in one and the same slot.

In addition, it would be convenient for such appointments if a talk room could be automatically created for all those who are registered in the slot (i.e. a common talk room).

**Comment by DaleJP** [comment]
I also need to adjust the number of slots in the same time period.

I wish to use it for our part-time Teaching Assistant shifts at our school.

The team can look at the available shifts and book them according to their availability.

I also want prospective parents to book slots for open days when we have multiple places available.

Sometimes we need 1, 2 or 3 people.

I've been trying to find a way to do it until I saw this post. 

Otherwise, this app is perfect. Almost exactly what we need.
