### ISSUE TITLE
Date Time doesn't display

### ISSUE THREAD

**Issue by SteBoun** [SergeyMosin/Appointments#357]
Hello,

When I post an appointment on this application. I success to use variable $eventData['attandeeTel'] and I receive an SMS.
But $eventData['DateTime'] is always null. I can't personalize the message.
My code in below :
[notification.txt](https://github.com/SergeyMosin/Appointments/files/9476005/notification.txt)
Any Help ?

**Comment by SergeyMosin** [comment]
Can you please send me the `.ics` file for this appointment. sergey [at] srgdev.com 

![image](https://user-images.githubusercontent.com/10747559/188127615-bcc47921-9fcf-45f4-bc6a-e20e1cec1d08.png)

**Comment by SteBoun** [comment]
Click on this link :
https://intra.talmontsainthilaire.fr/s/crTTX77ScYKExzJ

**Comment by SergeyMosin** [comment]
I think I the problem might be in you code here:
``
/*    $date=$eventData['dateTime'];*/
$date = isset($eventData['dateTime']) && is_array($eventData['dateTime']) ?
``
 Specifically with the `is_array($eventData['dateTime'])` check because the `$eventData['dateTime']` is not an array. It is a [DateTime object](https://www.php.net/manual/en/class.datetimeinterface.php).

See this example
https://github.com/SergeyMosin/Appointments/blob/f181e7cdd42fab076bd50690ce3d8611bfb5dea4/tests/extensions/notifications.php#L56

**Comment by SteBoun** [comment]
Thank you very much for this help.
I'll contribute on your project ^^
