### ISSUE TITLE
Check for conflicts does not take notice of all day events

### ISSUE THREAD

**Issue by Sarmingsteiner** [SergeyMosin/Appointments#380]
For the check for conflicts, we are using our external Google Calendar.

Whilst the check for conflicts does work with short-period events, it does not work with all day events.
Neither with manually created all day events, nor with "public holidays calendar" provided by Google.
Unfortunately, (un)ticking the check box "Include all day events in conflict check" under "Settings - Advanced Settings" does not seem to have any effect.

We are running NC 25.0.1 (NC Hub 3).
Thanks for your ideas!

**Comment by SergeyMosin** [comment]
Google marks "all day" events as `Free`, please make sure you set them to `Busy` because only `Busy` events can block.
 
![image](https://user-images.githubusercontent.com/10747559/202852869-1a09591f-1e65-4ed0-8524-7239172952e8.png)

RE: public holidays calendar" provided by Google
Once again  "public holidays" are marked as `Free` therefor they will not block. 

![image](https://user-images.githubusercontent.com/10747559/202853025-8430f7a2-bd35-46e5-ac11-8e5bab6339a1.png)

**Comment by Sarmingsteiner** [comment]
Thanks againg for the super-fast reply and the hints with busy / free.
So we have to find a work-around for public holidays, since this calendar resp. its entries cannot be changed to "busy".
