### ISSUE TITLE
documentation link broke

### ISSUE THREAD

**Issue by KiaraGrouwstra** [SergeyMosin/Appointments#381]
The readme ends with a link to rendered documentation.
Unfortunately, this link seems broken.

**Comment by SergeyMosin** [comment]
Thanks for the report. I think it is a bug in the [htmlpreview](https://github.com/htmlpreview) library the issue is here: https://github.com/htmlpreview/htmlpreview.github.com/issues/48

Just FYI, documentation is also available in the `Help/Tutorial` section.

![image](https://user-images.githubusercontent.com/10747559/202875021-3a066df5-65f1-4e64-bb22-e35e374aca4a.png)

rel #167
