### ISSUE TITLE
When creating timeslots in the weekly template, the timezone shows as Denver, US, but I'm in Europe

### ISSUE THREAD

**Issue by JMoVS** [SergeyMosin/Appointments#394]
Hi,

I have an issue with my weekly template now as the weekly template has the events entered into "Denver" timezone but I'm in CET so the slots end up in the middle of the night and I found no way to set the timezone of the weekly template - is there a way to set the timezone?

<img width="1086" alt="grafik" src="https://user-images.githubusercontent.com/7354506/212659392-bdc5649e-fd8b-4cb0-bc0f-a8928f1679c0.png">

**Comment by SergeyMosin** [comment]
There is a way to set a time zone, but it has to be done in the Calendar App, because:
1. Template time zone depends on the destination calendar used for template
2. A calendar time zone is set when it is created

So in your case:
1. Go to Calendar App settings (see image)
2. Note the current time zone
3. Set the timezone you want, CET I assume
4. Create a new calendar like "Appointments CET"
5. Optionally, go back to Calendar App settings and reset the time zone back to what ever it was in step 2
6. Go to Appointments App and change the calendar for the template to the one you created in step 4

![image](https://user-images.githubusercontent.com/10747559/212692343-636396c1-ecce-4f6e-b84d-b9a5e9b0194e.png)

**Comment by JMoVS** [comment]
I just checked and the calendar app already shows 
<img width="299" alt="grafik" src="https://user-images.githubusercontent.com/7354506/212712665-856fb496-01ce-446c-bdde-659b2fdc6883.png">


So not sure why the appointsments app wouldn't like that. Do I have to set it to something specific rather than having it on automatic?

**Comment by JMoVS** [comment]
Actually just checked - I set the calendar app to Berlin time, then switched to Appointments and went to "weekly template" and again saw Denver:
<img width="450" alt="grafik" src="https://user-images.githubusercontent.com/7354506/212713184-440e87b2-3a5c-4115-a89a-efd02e15c9ca.png">

**Comment by SergeyMosin** [comment]
Can you also check `Raw Calendar Data` in Appointments App `Settings > Advanced Settings > Debugging > Get raw calendar data`

**Comment by JMoVS** [comment]
> But did follow steps 4 and 6
> 
> > 4. Create a new calendar like "Appointments CET"
> > 5. ...
> > 6. Go to Appointments App and change the calendar for the template to the one you created in step 4
> 
> Every calendar can have it's own time zone, which is assigned at calendar create time. The calendar you selected as the destination in the Appointments App can have a different time zone set when it was created. Can you please create a new calendar and then use it as the Destination in the Appointments App.

I am not using a calendar for the source timeslots, I'm using the "weekly template" mode.

**Comment by JMoVS** [comment]
> Can you also check `Raw Calendar Data` in Appointments App `Settings > Advanced Settings > Debugging > Get raw calendar data`

sure - which calendar is the "weekly template" calendar?

**Comment by JMoVS** [comment]
I think I begin to understand, yet I don't know why - my main calendar seems to have the time zone set to "Denver" - is that something that I can change in the nextcloud backend for this calendar?
