### ISSUE TITLE
Odd 404 errors, not working - Nextcloud 18.0.3, Appointments 1.1.10, Calendar 2.0.2

### ISSUE THREAD

**Issue by jimoquinn** [SergeyMosin/Appointments#40]
Not sure what is going on here, but think I'll need some help figuring it out.  Did an install of NC 18.0.3 on Ubuntu 19.10 with Appointments 1.1.10 and Calendar 2.0.2.  Installed a bunch of other apps as well and so far they are working without any issues.  

After importing some contacts, creating a few calendars, I then loaded Appointments and filled out the info in the Settings area.  I then selected my calendar to use for appointments, added them to the calendar and nothing happened.  

Enabled debug tools and there are a number of 404 errors involving this URL:  https://sb.financialpubs.us/svg/core/places/calendar?color=8768bd.  You can see them in the screen shot below:
*  https://i.imgur.com/hIYaeEY.png

Also get this "no root" error:
*  https://i.imgur.com/Z0jvxCr.png

Any thoughts on what could be causing this?  This is the 3rd Nextcloud install that has this issue, I've uninstalled and reinstalled the apps, but so far can't get it fixed.

**Comment by SergeyMosin** [comment]
The 404s are referring to the wrong path to icons and will be fixed in the next release, but should not effect the app's functionality. 
The ``no root element found`` error is not from the appointments app, but it looks like something might be wrong with the "taskcal" calendar.

However, the ``data-state: 5`` message indicates that there are no appointments in the selected calendar withing the requested time range.
![ds5](https://user-images.githubusercontent.com/10747559/78356792-3abcc400-757e-11ea-8649-7e1a4dad363b.jpg)

Can you check if previously added appointments show up in the "Add Appointments" section when you add more appointments to the same week ??
![apn](https://user-images.githubusercontent.com/10747559/78357585-b53a1380-757f-11ea-8406-6201bd3cb83a.jpg)

Thank you.

**Comment by jimoquinn** [comment]
I can't get appointments to appear when I use "Add Appointments".  They won't show on the Appointments nor on the Calendar.  Actually, the calendar doesn't appear at all when I visit the Appointments page.  I can add events from the Calendar page.  Here is a screen shot:

*  https://imgur.com/a/bHiwKJd

I deleted the TaskCal calendar just in case it was the source of the problem.  Didn't fix it though.  Also I've disabled all ad blockers, disabled FireFox's tracking protections, and tried Chrome.  

I can give you access to this NC install if that would be helpful (likely faster than going back and forth here).  Email me at jim.oquinn@gmail.com.  Also, here is a video that may prove to be helpful as I try various settings/features in the calendar and appointments:

*  https://youtu.be/T1RLil8fSu0

**Comment by SergeyMosin** [comment]
In the "Add Appointments" section can you try the drop down menus...

![aap](https://user-images.githubusercontent.com/10747559/78366850-1fa68000-758f-11ea-8d34-cc7f1b063e8c.jpg)

You can also drag the time-slots up down

**Comment by jimoquinn** [comment]
Quick question, I have encryption enabled.  Would that cause an issue?

**Comment by SergeyMosin** [comment]
> Quick question, I have encryption enabled.  Would that cause an issue?

No it should not cause any issues, but there were some problems with Nextcloud encryption in general on certain AWS configurations. 
Were you able to add appointments in the "Add Appointments" section as per https://user-images.githubusercontent.com/10747559/78366850-1fa68000-758f-11ea-8d34-cc7f1b063e8c.jpg ?
