### ISSUE TITLE
Feature Request: Clickable Locations

### ISSUE THREAD

**Issue by redispade** [SergeyMosin/Appointments#417]
Would it be possible to add a second, optional form on the User/Organization info for a Google maps link, that if filled, the Location becomes clickable on the public form(and possibly the calendar invite). This way, a business(or even individuals) can set their own Name and address, and put a maps link too. This would allow to put a zoom link too if the meeting is online.

**Comment by SergeyMosin** [comment]
There are no plans to add custom HTML to the form.

However, links ( and even HTML ) are supported in `Appointments > Settings > Email Settings > Additional CONFIRMATION/VALIDATION email text` so you can add directions and links to maps or zoom. It will be sent to attendees once they confirm their Appointments ( or validate their email address )

More text can also be added to attached `.ics` file attachments in  the `Additional ICS file description` section, but I would not put HTML here because, some calendar apps might not display it properly.
