### ISSUE TITLE
name-value from nextcloud prevents usage of buttons

### ISSUE THREAD

**Issue by fischtag** [SergeyMosin/Appointments#421]
When the embedded calendar loads on the external page the name-value of the Nextcloud instance is displayed from the theming and after loading it covers the month and all buttons like day / week / month etc. and prevents them from being used. The calendar preview itself and booking features works fine.

**Comment by SergeyMosin** [comment]
@fischtag Can you please post a screen-shot. Thanks.

**Comment by fischtag** [comment]
While loading ...
![loading-calender](https://github.com/SergeyMosin/Appointments/assets/18589744/e8ded6f9-3a84-421c-8164-ee8d7f6d4c92)
After retrieving the calenders data, the "name from theming" overlays all buttons ...
![after-loading](https://github.com/SergeyMosin/Appointments/assets/18589744/7f2b29b3-54e1-4944-96d8-4ee5848725b9)
Thanks for looking into this, i hope you can reproduce or give me a hint.

**Comment by SergeyMosin** [comment]
This bug is not related to this Appointments app and can be reproduced on any calendar(even a new empty one)

@fischtag please open a new issue/bug report with NC Calendar App dev teams at https://github.com/nextcloud/calendar/issues

![image](https://github.com/SergeyMosin/Appointments/assets/10747559/295c9a62-7e38-49f6-af91-417bb6a94676)
