### ISSUE TITLE
Error in log file since appointments version 2.0.0

### ISSUE THREAD

**Issue by liaham** [SergeyMosin/Appointments#482]
There is a recurring error in nextcloud log file since version 2.0.0 of appointments app. Please note 'Fehler' is German and means 'Error' in English.

![grafik](https://github.com/SergeyMosin/Appointments/assets/43378236/b9c12802-826e-468a-b41e-2d4d52619e0f)

**Comment by ive-online** [comment]
Hello ! Unfortunately, the same occurrence is here. The errors are significantly caused by appointments. Regards.

![Screenshot_20240306_093222](https://github.com/SergeyMosin/Appointments/assets/160873934/5baad8b2-b083-4dc4-9fd4-d875e4e5d481)
![Screenshot_20240306_093146](https://github.com/SergeyMosin/Appointments/assets/160873934/f7e6e1e0-a953-4d4e-af5b-2fdf6127474d)

**Comment by liaham** [comment]
Thank you very much for your quick response! 

Good to know that there is no serious error behind.
