### ISSUE TITLE
confirming fails

### ISSUE THREAD

**Issue by stefangweichinger** [SergeyMosin/Appointments#485]
nextcloud-28.0.3,  appointments-2.0.1

When I test adding an appointment while not logged into NC (2nd browser, for example), I get to the point where I click the link in the received email .. this gets me to the website again, to confirm there.

Then I get "page not found".

My NC runs at `https://my.tld/nextcloud/` and the page not found seems to be messed up:

```
https://my.tld/nextcloud/index.phpintments/pub/....
```

I assume this should be 

```
https://my.tld/nextcloud/apps/appointments/pub/....
```

or so.

Did I configure something wrong? How to fix this? Thanks in advance.

**Comment by SergeyMosin** [comment]
Can you please check if the URL that appointments displays in the "Show URL/link" dialog has `index.php` in it or not. 
Example: `https://my.tld/nextcloud/apps/...` vs `https://my.tld/nextcloud/index.php/apps/...`

![image](https://github.com/SergeyMosin/Appointments/assets/10747559/bc996b9b-063e-45d6-89d2-c7c03aaf4c52)

**Comment by stefangweichinger** [comment]
It doesn't:

```
https://my.tld/nextcloud/apps/appointments/pub/ilbkXXXYYY/form
```

**Comment by SergeyMosin** [comment]
Thank you. I am trying to replicating this.

**Comment by stefangweichinger** [comment]
Just in case: I fiddled with settings as mentioned in (closed) https://github.com/SergeyMosin/Appointments/issues/473#issuecomment-1972878779

I assume it's not related, just telling. Thanks.

**Comment by SergeyMosin** [comment]
Actually it might be related to embedding.

Do you have something like this in your embedding script ?
```
... substr($src, 0, -4) . 'cncf?d=' ...
```
can you make sure it is '-4' and not '4'. If possible can you send me your embedding scripts to sergey [at] srgdev.com .

**Comment by stefangweichinger** [comment]
I don't know about *any* embedding scripts ... I only added the options (`occ config:app:set`) as mentioned.
I am not that competent in terms of web-development ... only following instructions here (as far as I understand them).

**Comment by SergeyMosin** [comment]
I assume you are trying to embed the appointments page into an `iFrame` if you set `emb_afad_<YourUserNameHere>` and/or `emb_cncf_<YourUserNameHere>` vars via `occ` as per #473 .
In order to figure out if the problem is in the embedding part or the core part can you please clear(`occ config:app:delete`) both `emb_afad_...` and `emb_cncf_...` vars try to book an appointment via not embedded URL.

**Comment by stefangweichinger** [comment]
will try asap. thx

**Comment by SergeyMosin** [comment]
Thank you.

**Comment by stefangweichinger** [comment]
PM sent. Thanks.

**Comment by stefangweichinger** [comment]
Just updated and tested again: works now for me! Thanks!

**Comment by SergeyMosin** [comment]
FYI: The error was actually caused by `IRequest->getRequestUri()` ( https://nextcloud-server.netlify.app/classes/ocp-irequest#method_getRequestUri ) , which is a part of the core API. I was able to replace this function call, but there are other places in NC code that use this function.

**Comment by xprofiler** [comment]
> Can you please check if the URL that appointments displays in the "Show URL/link" dialog has `index.php` in it or not. Example: `https://my.tld/nextcloud/apps/...` vs `https://my.tld/nextcloud/index.php/apps/...`
> 
> ![image](https://private-user-images.githubusercontent.com/10747559/310882557-bc996b9b-063e-45d6-89d2-c7c03aaf4c52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MTM2NzgsIm5iZiI6MTcxMTcxMzM3OCwicGF0aCI6Ii8xMDc0NzU1OS8zMTA4ODI1NTctYmM5OTZiOWItMDYzZS00NWQ2LTg5ZDItYzdjMDNhYWY0YzUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDExNTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3YWFiMDgzOGM4NzljOGVjOTVmNWM2OGY5ZTFjNDk5M2RiOTE4YmQyODdhMTcwMzcxZmIzNDI1MjlkZjgyMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8AOCZ2sNnsUa3dAfvYMpCGiB8k-FJCotXmlllpvRz_0)

Only a note, because I found this issue while having the problem, that the links in the confirmation mail were broken:
I am using the appointment form as an iFrame in another website. After changing the configuration to use pretty URLs described [here](https://docs.nextcloud.com/server/latest/admin_manual/installation/source_installation.html#pretty-urls), I forgot to update the iFrame URL on my website. It was showing correctly, because the link was working with and without index.php in the URL string. Only the confirmation mails were containing wrong URLs with are resulted in page-not-found errors.
Thanks for the hint to the appointment URL!
