### ISSUE TITLE
Appointment confirmed mail not translated

### ISSUE THREAD

**Issue by EkkiBrue** [SergeyMosin/Appointments#498]
Hi Sergey.

Since updating to 2.0 the confimation mail is always in english. Now I´m on 2.07 and the bug is still there. NC is set to german - so is the OS / Browser

Text in mail is like:

```
Appointment is confirmed

MYMAILTEXT

Thank you

To cancel your appointment please click: Cancel Appointment 

```
Interestingly all other mails seem to be translated in german (e.g. status changed, action required etc.)

Just found that the main language for cron / email is set to "en". Can I change this or is this completely unrelated to the topic? It´s the only place where I could change any language settings though...

![image](https://github.com/SergeyMosin/Appointments/assets/6376844/4aceedc9-9047-4690-abee-7c1414dd0a6a)

**Comment by SergeyMosin** [comment]
I can not replicate this for confirmation emails (see images below.)

>Just found that the main language for cron / email is set to "en". Can I change this or is this completely unrelated to the topic? It´s the only place where I could change any language settings though...

This only applies to "Reminder" emails because they are triggered by a system cron job. The `default_language` property is set by admin in NC `config.php` ( more info:  https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#default-language ) . There are plans to add a workaround for this, but it probably will be a while until it is implemented.

![image](https://github.com/SergeyMosin/Appointments/assets/10747559/952395e7-48aa-4bf9-b8e5-58950e9c25a5)

![image](https://github.com/SergeyMosin/Appointments/assets/10747559/4e0ab2a1-657b-460b-8c5d-2d11a5383927)

![image](https://github.com/SergeyMosin/Appointments/assets/10747559/299da1de-17c8-424e-82e8-c9a1f7832585)

**Comment by EkkiBrue** [comment]
Strange. Now the phenomenon does not occur anymore and the problem seems to be gone since the release of v2.10.

Thanks ;)
