### ISSUE TITLE
It would be good with the ability add single days to schedule and not only a whole week.

### ISSUE THREAD

**Issue by small1** [SergeyMosin/Appointments#5]
It would be good with the ability add single days to schedule and not only a whole week.

Me for example needs bookable meetings on Fridays

**Comment by nolens** [comment]
> It would be good with the ability add single days to schedule and not only a whole week.

Absolutely!

**Comment by nolens** [comment]
> It would be good with the ability add single days to schedule and not only a whole week.

As a workaround, you can create the appointment row, and then delete those slots that you don't want to offer. Deletion of these dates also works on connected calendar apps (like MacOs Calendar app). 

@SergeyMosin :  I am the donor of the bounty source that you are claiming. Can you please contact me on a private chat, so that we can discuss what is still needed to release the bounty. Thanks, Sergey!

**Comment by nolens** [comment]
@small1 
this issue is fixed with version 1.10
Please close this issue.
