### ISSUE TITLE
Uncaught ReferenceError: OC is not defined

### ISSUE THREAD

**Issue by markuman** [SergeyMosin/Appointments#519]
latest version is not usable anymore.  
nothing on a public URL is clickable anymore.

Browser console prints: Uncaught ReferenceError: OC is not defined

appointments 2.1.4 on nextcloud 29.0.1

**Comment by markuman** [comment]
![Unbenannt](https://github.com/SergeyMosin/Appointments/assets/3920157/8006d053-9fb5-46ec-b22f-69bef8b95183)

Also broken  on nextcloud 29.0.2.  
And also broken in both, firefox and chrome browser.

**Comment by SergeyMosin** [comment]
`OC*` related JS errors can safely be ignored. They are there because some large NC related .js files are not loaded on the public page in order to make it faster. 

However the `data-state: 4` message indicates that your page is not enabled. More info... 

[appt-enable.webm](https://github.com/SergeyMosin/Appointments/assets/10747559/20901c46-986f-4541-a02a-998179aa9e2c)

**Comment by markuman** [comment]
Ah damn. Thank you for your quick support!
