### ISSUE TITLE
Feature Request: Multiple appointment types with differrent settings

### ISSUE THREAD

**Issue by 0x4E4448** [SergeyMosin/Appointments#559]
Appointments v2.2.0
Nextcloud v30.0.2

I'm attempting to create different appointment types with different settings (Status call vs Working session). The status call appointments are 30m or 1hr and the working sessions are 1hr, 2hr, 3hr, or 4hr.

I can edit the appointment template and add overlapping appointments with the different settings but if I edit the last one (to remove durations that exceed my availability), it edits a completely different appointment. When configured, it combines all the types and the way it is displayed is not visually appealing, in my opinion, from a requestor standpoint and it isn't manageable from an administrative standpoint.

I looked into adding an additional text field but I can't alter the durations depending on the selection.

I suggest correcting the overlapping appointment issue and then adding a dropdown to select an appointment type and only displaying appointment times and durations for that type of appointment.

**Comment by 0x4E4448** [comment]
This seems to be similar to #360 but that request does not address different duration times.

**Comment by 0x4E4448** [comment]
> I can edit the appointment template and add overlapping appointments with the different settings but if I edit the last one (to remove durations that exceed my availability), it edits a completely different appointment. When configured, it combines all the types and the way it is displayed is not visually appealing, in my opinion.

To describe my specific situation- add (12) 30m or 1hr appointments and space the every 30 minutes (Step 1) then you add (6) 1hr, 2hr, 3hr, or 4hr appointments it will add the second set of appointments start at 8am (Step 2). You then drag the appointments to overlap with the existing appointments (Step 3). Edit the last appointment to reduce it to a 1hr duration, the penultimate to a 1hr or 2hr duration, and so on (Step 4). At some point one of the previous 12 appointments will change to a 1hr appointment with the same name as the one you edited.

Step 1
![Screenshot from 2024-11-17 23-51-28](https://github.com/user-attachments/assets/bcb8b6ae-1284-4807-8145-5365241bf612)

Step 2
![Screenshot from 2024-11-17 23-52-25](https://github.com/user-attachments/assets/22ba13f3-cc39-4a60-9ec7-e54b20bb67cb)

Step 3
![Screenshot from 2024-11-17 23-53-12](https://github.com/user-attachments/assets/654b4a5a-ae53-4fdb-b270-9598240366e9)

Step 4
![Screenshot from 2024-11-17 23-53-41](https://github.com/user-attachments/assets/9b5b12ea-5df7-4890-9c0c-db1bb930ab13)

**Comment by SergeyMosin** [comment]
@0x4E4448 Thank you for the report. I can replicate the bug where editing one time slot effect the other. This should be fix in the next release.

Simplified bug repro. flow note:
1. Create one 45 min time-slot
2. Create one 30 min time-slot
3. Edit the 30 min slot
4. The 45 min slot is changed instead of the 30 min one :boom: :bug:

**Comment by SergeyMosin** [comment]
The editing issue where changes applied to multiple time-slots is fixed in v2.3.0

The _dropdown to select an appointment type_ is not planned for now but might be implemented eventually as a part of #157 

Alternatively, a `Directory Page` can be used for better presentation of different appointment types. More info here: https://github.com/SergeyMosin/Appointments/issues/333#issuecomment-1124983843 and here: https://github.com/SergeyMosin/Appointments/issues/21#issuecomment-696738211
