### ISSUE TITLE
"1:Can not get calendar timezone"

### ISSUE THREAD

**Issue by Rello** [SergeyMosin/Appointments#58]
- I want to add a non-floating timeslot.
- The pop-um message confirms that the entries are added to calendar
- caladd returns a status 200
- return-content of caladd tells "1:Can not get calendar timezone"
- entries are not added to the calendar
.
- personal calendar is selected correctly
- floating works as expected

can you evaluate?

**Comment by SergeyMosin** [comment]
Can you check your calendar timezone

![cal_tz](https://user-images.githubusercontent.com/10747559/79929095-b63dc280-8412-11ea-8f31-fd5025f9cd5c.jpg)

Thank you

**Comment by tcitworld** [comment]
> Calendar's color seems to be missing from the backend as well.

https://github.com/nextcloud/server/pull/17148

About the timezone issue, cc @georgehrke

**Comment by SergeyMosin** [comment]
Fixed in v1.4.6 Appointment with actual(non floating) timezones are shown/processed in visitors time

----
12:00PM Appointment in Actual Timezone (America/New_York):
![actual_timezone](https://user-images.githubusercontent.com/10747559/80231078-de9b0c00-8620-11ea-9d6d-36beb429d8ca.jpg)

----

12:00PM Appointment in FLOATING Time:
![floating_timezone](https://user-images.githubusercontent.com/10747559/80231086-e195fc80-8620-11ea-9bfa-58fa786c0e6f.jpg)

TODO: Update Help/Tutorial
