### ISSUE TITLE
[BUG] Don't get mails

### ISSUE THREAD

**Issue by Dubidubiduu** [SergeyMosin/Appointments#72]
In addition to my request in #67: Actually sending mails only worked once. I don't get it to work again. So ppl write an additional mail asking if I got the appointment (which I got, appoinments update my calendar in a second).

Sending testmail via https://cloud.sozis-tiere.de/index.php/settings/admin works.

Using Appointments 1.4.11 and NC 18.0.3.
![emailserver](https://user-images.githubusercontent.com/34820982/81179523-0cca0580-8faa-11ea-8155-ebf68e061884.png)

**Comment by SergeyMosin** [comment]
Are there any messages in the NC logs or the mailserver logs ?

**Comment by SergeyMosin** [comment]
Do you receive notification emails when these options are checked ?

![email_notifications](https://user-images.githubusercontent.com/10747559/81181541-9d88ed00-8f7a-11ea-9d58-d96c626b6d48.jpg)

**Comment by Dubidubiduu** [comment]
Thanks again for your vastly fast answer!

> Are there any messages in the NC logs or the mailserver logs ?
Haven't found anything in NC logs. And I don't think I have access to my mailserver logs, at least haven't found them yet.

> Do you receive notification emails when these options are checked ?
Nope.

Can I do something else? Have a look in database or so?

**Comment by SergeyMosin** [comment]
When you add an event with an attendee in the **Calendar App** (nor Appointments App) does the attendee receive the _invitation_ email ?

**Comment by Dubidubiduu** [comment]
Nope, no one gets one, checked with calendar.

Could be connected to activity app?
https://cloud.xx.de/index.php/settings/admin/activity or https://cloud.xx.de/index.php/settings/user/activity

- A calendar was modified
- A calendar event was modified
- A calendar todo was modified

But even when there is a misconfiguration, at least the external appointment user should get one..?!

Part of my config.php

 25   'mail_from_address' => 'automail',
 26   'mail_smtpmode' => 'smtp',
 27   'mail_smtpauthtype' => 'LOGIN',
 28   'mail_domain' => 'xx.de',

   'mail_smtpauth' => 1,
 43   'mail_smtphost' => 'mail.xx.de',
 44   'mail_smtpport' => '587',
 45   'mail_smtpname' => 'automail@xx.de',
 46   'mail_smtppassword' => 'qq',
 47   'mail_smtpsecure' => 'tls',

57   'mail_sendmailmode' => 'smtp',

**Comment by SergeyMosin** [comment]
If both Calendar and Appointments can not send out an email I would assume that the problem is somewhere else. However...

https://gist.github.com/SergeyMosin/e4d426f794717d16d968e98a2bf7b86c is the link to modified DavListener.php file. It has addition debugging/logging code. Log lines starting with ``APPT_EMAIL_DEBUG: ...`` should tell exactly where the email problem in appointments app is. If you see ``APPT_EMAIL_DEBUG: All checks passed.`` than the problem is elsewhere.

To start debugging:
1. replace contents of your ``/path/to/nextcloud/apps/appointments/lib/Backend/DavListener.php`` with the contents of the file provided in the link.
2. Book a test appointment
3. Check NC logs for ``APPT_EMAIL_DEBUG: ...`` info

The original DavListener.php is found at https://github.com/SergeyMosin/Appointments/blob/master/lib/Backend/DavListener.php , put it's contents in to your DavListener.php when your finished debugging.

**Comment by Dubidubiduu** [comment]
Thank you very much.

I got this message: "APPT_EMAIL_DEBUG: Not this user's calendar" and created a new issue #73
