### ISSUE TITLE
Duplicate Appointment Slots by Week or Month

### ISSUE THREAD

**Issue by buggify** [SergeyMosin/Appointments#77]
Currently I can add appointment slots one day at a time, duplicating one day at a time. I would like to duplicate one week at at time, monthly, or indefinitely. I tried to add appoint slot, save to calendar, then duplicate on the calendar side, hoping that Appointments would recognize the availability, but instead Appointments indicated "no appointments available" when I did that.

My Tentative Available Schedule never changes, so allowing me to duplicate a single day forever would be amazing.

**Comment by SergeyMosin** [comment]
This is similar to #39 (recurring appointments).
I am going to close this one and the discussion should continue over at #39 
There are few things to consider like:
1. What happens when you manually add an event (in an other calendar) that conflicts with recurring/auto-generated appointments. ?
2. How about holidays or random days-off?
3. It should be easy to switch between or combine auto-generated and manually created appointments

I'll post updates once I have a clear game plan, but it is somewhat of a large task.
