### ISSUE TITLE
NC 18.05 & Appintments 1.5.0 not all confirmations mails are send

### ISSUE THREAD

**Issue by dkyme** [SergeyMosin/Appointments#94]
Hello Sergey,
I got reports from some of my students, that they haven't received the confirmation Mail for their appointments.
Nothing in Spam folders. No pattern of specific Email providers to find.
Where can I check for diagnosis of this issue?
The System inbuilt Logging app gives me no Information.

I'm on a shared host, without ssh, if that is relevant.

Thanks for your help

**Comment by SergeyMosin** [comment]
There are two emails sent, first one asking to confirm the appointment, the second one saying that the appointment is confirmed. Are they not receiving both?

Do you have access to the mail server logs ?

Can you temporary replace one of the files in your nextcloud/appointments app installation folder? If so, I can make a file with extend logging enabled and with that you will be able to trace the issue.

**Comment by dkyme** [comment]
Since they don't get the mail to confirm, they don't get the second one, I assume

No, I don't have access to the mail server logs, but I could replace the file.

**Comment by SergeyMosin** [comment]
@dkyme 
Here is the link to DavListener.php file https://gist.github.com/SergeyMosin/c55e551f2d6616299fe69ea357b8048d
You need to replace the contents of your ``/path/to/nextcloud/apps/appointments/lib/Backend/DavListener.php`` with the contents of the above file.
When done, the original file for v1.5.0 can be found at https://github.com/SergeyMosin/Appointments/blob/68f839e2a85eb4e456c4d7128942343f711012ed/lib/Backend/DavListener.php

This should not interfere with regular operations,  it just has additional logging enabled, the messages will be logged with level error so they are easier to see. Most messages will have an email address attached, you will be able to look for the ones that do not get the email. There are APPT_DEBUG_ERR, APPT_DEBUG_WARN and APPT_DEBUG_INFO prefixes for all the messages. If you see APPT_DEBUG_ERR or APPT_DEBUG_WARN messages please let me know. The ``APPT_DEBUG_INFO (email@address.com): message has been sent to your mail server`` would indicate that the problem is somewhere else. 

This is what the log could look like:
![email_debug_2](https://user-images.githubusercontent.com/10747559/84060442-33ed6b80-a98a-11ea-93bb-10ed8ecfe0cc.jpg)

**Comment by dkyme** [comment]
@SergeyMosin 
I have asked the same people with issues to book an appointment again, after changing the file.
No issues this time.
I keep the change for a while to see if it happens again.
What I changed before the debug file:
Switched the 

- Settings of the Email Server from Sentmail to SMTP
- Background jobs from Ajax to WebCron (5min)

Maybe that's the reason?
Anyways, the issue can be closed. everything works as expected.

Thank you

**Comment by dkyme** [comment]
@SergeyMosin ,
here comes the debug message.

[no app in context] Error: APPT_DEBUG_ERR: bad data

POST /index.php/apps/appointments/form?v=1591700852859
from 2.244.87.145 by xxx.xxxx at 2020-06-09T11:08:07+00:00

Checking the exported ics, all of the failed appointments have:
ORGANIZER;CN=Admin.User;SENT-BY="mailto:neuigkeiten@example.de":mailto:kurse@example.de

while the working ones have:
ORGANIZER;CN=Admin.User;SCHEDULE-AGENT=CLIENT:mailto:kurse@example.de

Maybe it is because of my workaround of #54 
First I created 6 appointments with the app _before update to 1.5.0_, pushed them on the same time.
Then I copied them via Thunderbird/Lightning to the next week.

After the update to 1.5.0 I changed the Contact Information Setting from neuigkeiten@ to kurse@

Thank you for the app anyways

**Comment by SergeyMosin** [comment]
``... SCHEDULE-AGENT=CLIENT ...`` is a required parameter. It prevents nextcloud native scheduling plugin from sending extra/conflicting emails. This parameter was introduced before v1.5.0 (probably in v1.3.*). I it should not get lost when the appointments are copied via Thunderbird/Lightning, unless it is some king of _scheduling message_, specs: https://tools.ietf.org/html/rfc6638#section-7.1

P.S. Some form of weekly templates/recurrence should be available in the next major release

**Comment by SergeyMosin** [comment]
There is also ``Skip email validation step`` option if all else fails...

**Comment by SergeyMosin** [comment]
You can also try https://github.com/SergeyMosin/Appointments/issues/100#issuecomment-653780651
