### ISSUE TITLE
Missing translations in french

### ISSUE THREAD

**Issue by El-Gavy** [SergeyMosin/Appointments#98]
Hi,

Some translations appear to be missing in french : 

![image](https://user-images.githubusercontent.com/26960332/84320795-838e8b80-ab72-11ea-89dc-196006952784.png)

I can translate these strings easily (french guy here) but how to contribute / which file to edit?

**Comment by SergeyMosin** [comment]
v1.5.2 includes latest translations.

**Comment by El-Gavy** [comment]
> v1.5.2 includes latest translations.

Great ! I'll update tonight !

Do you have admin rights on Appointments project in Transifex ? Because There is still a typo for which a suggestion has been proposed and upvoted two times, but that no one has validated. It is frustrating because it is one of the most visible sentences in the public forms.
https://www.transifex.com/nextcloud/nextcloud/translate/#fr/appointments/289180983

**Comment by SergeyMosin** [comment]
> Do you have admin rights on Appointments project in Transifex

No sorry.

If all fails you can try editing your local ``/path/to/nextcloud/apps/appointments/l10n/fr.js`` and ``/path/to/nextcloud/apps/appointments/l10n/fr.json`` files. I am not sure if it's going to work because the translations might be cached somewhere else and will be OVERWRITTEN by the next update.

Good luck.
